### ISSUE TITLE
Broken lldb build under OS X Yosemite/Clang 6

### ISSUE THREAD

**Issue by sebastiang** [Keno/Cxx.jl#85]
In order to use `Cxx.jl`, I am building Julia (and LLDB) from `master` with the given `Make.user`, but I get the following error. I am running Yosemite and XCode/clang 6.2. Some Googling suggests that there may be some configuration changes to make in the LLDB branch, but I admit that is a bit beyond my understanding. 

    llvm[5]: Linking Release+Asserts Shared Library liblldb.dylib
    Undefined symbols for architecture x86_64:
      "lldb_private::Terminate()", referenced from:
          lldb::SBDebugger::Terminate() in liblldbAPI.a(SBDebugger.o)
      "lldb_private::Initialize(llvm::sys::DynamicLibrary (*)(std::__1::shared_ptr<lldb_private::Debugger> const&, lldb_private::FileSpec const&, lldb_private::Error&))", referenced from:
          lldb::SBDebugger::Initialize() in liblldbAPI.a(SBDebugger.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[5]: *** [/Users/sebastian/dev/julia-cxx/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/liblldb.dylib] Error 1
    make[4]: *** [install] Error 1
    make[3]: *** [install] Error 1
    make[2]: *** [install] Error 1
    make[1]: *** [/Users/sebastian/dev/julia-cxx/usr/lib/libLLVMCodeGen.a] Error 2
    make: *** [julia-deps] Error 2

**Comment by Keno** [comment]
Yep, I've got it, give me a few min.

**Comment by Keno** [comment]
Fixed by https://github.com/Keno/Cxx.jl/commit/ad33540cf81310eb46670f90dc16f7d76cf60732

**Comment by sebastiang** [comment]
Thanks, @Keno, that does seem to have done the trick! I admit to not knowing how a change in the `Cxx.jl` codebase can cause the `julia` build to succeed. There is now a further error, which I'll log.

**Comment by sebastiang** [comment]
Now getting an error compiling `codegen.cpp`, which is part of Julia so far as I understand. But a `julia` build from the same commit (`97b1870`) compiles correctly, so I assume this is more interaction with something `Cxx.jl` has pulled down. Any ideas?

    codegen.cpp:4250:35: error: use of overloaded operator '!=' is ambiguous (with
            operand types 'llvm::DIVariable' and 'long')
                  if (ctx.vars[s].dinfo != NULL) {
                      ~~~~~~~~~~~~~~~~~ ^  ~~~~
      codegen.cpp:4250:35: note: built-in candidate operator!=(const volatile class
            llvm::MDNode *, const volatile class llvm::MDNode *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(volatile class
            llvm::MDLocalVariable *, volatile class llvm::MDLocalVariable *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(const volatile class
            llvm::MDLocalVariable *, const volatile class llvm::MDLocalVariable *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(volatile class
            llvm::MDNode *, volatile class llvm::MDNode *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(class
            llvm::MDLocalVariable *, class llvm::MDLocalVariable *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(class llvm::MDNode *,
            class llvm::MDNode *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(const class
            llvm::MDNode *, const class llvm::MDNode *)
      codegen.cpp:4250:35: note: built-in candidate operator!=(const class
            llvm::MDLocalVariable *, const class llvm::MDLocalVariable *)
      1 error generated.
      make[1]: *** [codegen.o] Error 1
      make: *** [julia-src-release] Error 2

**Comment by ihnorton** [comment]
Have you updated your LLVM build lately? (`make -C deps update-llvm`)

**Comment by sebastiang** [comment]
Just created this source tree this morning to make sure I had a clean bug report. Nonetheless, I updated LLVM with the command above, and still get the same error.

**Comment by dvasiliu** [comment]
I have exactly the same error. I would really appreciate a solution. Thank you.

**Comment by Keno** [comment]
which one? What's your Make.user?

**Comment by dvasiliu** [comment]
Hi,

The error is the same:

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/Users/daniel/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/liblldb.dylib] Error 1
make[4]: *** [all] Error 1
make[3]: *** [all] Error 1
make[2]: *** [all] Error 1
make[1]: *** [llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMCodeGen.a] Error 2

Also, my Make.user file is :

override LLDB_VER=master
override LLVM_VER=svn
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override BUILD_LLDB=1
override USE_LLVM_SHLIB=1
override LLDB_DISABLE_PYTHON=1

Thank you very much for your reply.

Daniel

**Comment by Keno** [comment]
You cut off the actual error. If it's the same as the original issue, make sure you have the appropriate versions.

**Comment by dvasiliu** [comment]
Hi,

Thank you very much, the following is a longer printout:

llvm[6]: Compiling StringExtractor.cpp for Release+Asserts build
llvm[6]: Compiling StringExtractorGDBRemote.cpp for Release+Asserts build
llvm[6]: Compiling StringLexer.cpp for Release+Asserts build
llvm[6]: Compiling TimeSpecTimeout.cpp for Release+Asserts build
llvm[6]: Compiling UriParser.cpp for Release+Asserts build
llvm[6]: Building Release+Asserts Archive Library liblldbUtility.a
llvm[5]: Linking Release+Asserts Shared Library liblldb.dylib
Undefined symbols for architecture x86_64:
  "lldb_private::DynamicLoaderWindowsDYLD::Terminate()", referenced from:
      lldb_private::SystemInitializerCommon::Terminate() in liblldbInitialize.a(SystemInitializerCommon.o)
  "lldb_private::DynamicLoaderWindowsDYLD::Initialize()", referenced from:
      lldb_private::SystemInitializerCommon::Initialize() in liblldbInitialize.a(SystemInitializerCommon.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/Users/daniel/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/liblldb.dylib] Error 1
make[4]: *** [all] Error 1
make[3]: *** [all] Error 1
make[2]: *** [all] Error 1
make[1]: *** [llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMCodeGen.a] Error 2
make: *** [julia-deps] Error 2

**Comment by Keno** [comment]
Fixed in https://github.com/llvm-mirror/lldb/commit/f9d5ebafe446857ff805b078b90c8c400758acdd

**Comment by dvasiliu** [comment]
Hi, 

It sounds awesome ! I will try to recompile Julia again.

Best,

Daniel

**Comment by dvasiliu** [comment]
Hi Keno,

Thanks again for all the help. I was able to successfully compile julia but when I try to install Cxx I get the following:

INFO: Building Cxx
Tuning for julia installation at: /Users/daniel/julia/usr/bin
    CC /Users/daniel/.julia/v0.4/Cxx/deps/build/bootstrap.o
    LINK /Users/daniel/.julia/v0.4/Cxx/deps/usr/lib/libcxxffi.dylib
Undefined symbols for architecture x86_64:
  "lldb_private::DynamicLoaderWindowsDYLD::Initialize()", referenced from:
      lldb_private::SystemInitializerCommon::Initialize() in liblldbInitialize.a(SystemInitializerCommon.o)
  "lldb_private::DynamicLoaderWindowsDYLD::Terminate()", referenced from:
      lldb_private::SystemInitializerCommon::Terminate() in liblldbInitialize.a(SystemInitializerCommon.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [usr/lib/libcxxffi.dylib] Error 1
=================================[ ERROR: Cxx ]=================================

LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/Users/daniel/julia/usr/bin`, ProcessExited(2)) [2]
while loading /Users/daniel/.julia/v0.4/Cxx/deps/build.jl, in expression starting on line 16

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /Users/daniel/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

================================================================================
